apiVersion: v1
kind: Service
metadata:
  name: argocd-server-loadbalancer
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    name: argocd-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
