apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo-app
    repoURL: https://github.com/julscloudops/ManifestsForArgoCD 
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
