Version: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  namespace: demo-app
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "test-selfsigned"
spec:
  rules:
  - https:
      paths:
      - path: /
        backend:
          service:
            name: frontend
            port:
              number: 443
